---
# vars file for site
service_account_email: ansible@gastv-182201.iam.gserviceaccount.com
credentials_file: /Users/asrivats/Downloads/gastv-fe2339d71d49.json
project_id: gastv-182201
machine_type: n1-standard-2
image: ubuntu-1404