---
# tasks file for haproxy
- name: haproxy apt repo (Ubuntu)
  become_user: root
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.7"
    state: present
    update_cache: yes
  tags:
    - create

- name: install haproxy
  become_user: root
  apt: name=haproxy state=present
  tags:
    - create