---
# tasks file for GCE
 - name: Launch instances
   gce:
       instance_names: dev01,dev02,dev03,dev04
       machine_type: "{{ machine_type }}"
       image: "{{ image }}"
       service_account_email: "{{ service_account_email }}"
       credentials_file: "{{ credentials_file }}"
       project_id: "{{ project_id }}"
   tags:
    - create
 - name: Delete instances
   gce:
       instance_names: dev01,dev02,dev03,dev04
       machine_type: "{{ machine_type }}"
       image: "{{ image }}"
       service_account_email: "{{ service_account_email }}"
       credentials_file: "{{ credentials_file }}"
       project_id: "{{ project_id }}"
       state: absent
   tags:
    - delete