apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: load-test
  labels:
    app: php-apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: gcr.io/google_containers/hpa-example
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-service
spec:
  type: NodePort
  ports:
  - port: 4782
    targetPort: 80
    nodePort: 31313
    protocol: TCP
  externalIPs:
    - 35.184.144.14
    - 35.188.100.34
    - 35.193.246.140
  selector:
    app: php-apache
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-test-autoscale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: load-test
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 35