apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: load-test
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: web
   spec:
     containers:
       - name: front-end
         image: nginx
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-service
spec:
  type: NodePort
  ports:
  - port: 4782
    targetPort: 80
    protocol: TCP
  externalIPs:
    - 35.194.57.177
  selector:
    app: web